* initialize_class: Use c->state instead of old members (initializing,   initialized, now we also have a CLASS_ERROR state and return a   NoClassDefFoundError in this case (fixes mauve test).